### ISSUE TITLE
The bootstrap can be simpler

### ISSUE THREAD

**Issue by wenzeslaus** [tomorrownow/intro-to-geoprocessing-workshop#1]
The following block is not needed with reasonably current GRASS GIS, but that [may require PPA in Colab](https://github.com/ncsu-geoforall-lab/grass-gis-workshop-vanderbilt-2024/blob/main/colab_install.ipynb):

```
# Ask GRASS GIS where its Python packages are.
gisbase = subprocess.check_output(["grass", "--config", "path"], text=True).strip()
os.environ["GISBASE"] = gisbase
print(gisbase)
```

I think even 8.0 allows you to do (if that feels simpler):

```diff
- gj.init("./grassdata", "nc_basic_spm_grass7", "tutorial")
+ gj.init("./grassdata/nc_basic_spm_grass7/tutorial")
```

Or (if home should be explicit, but current directory makes sense to me too):

```diff
- gj.init("./grassdata", "nc_basic_spm_grass7", "tutorial")
+ gj.init("~/grassdata/nc_basic_spm_grass7/tutorial")
```

**Comment by cwhite911** [comment]
Fixed this.
